
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

public class Studentnummer extends javax.swing.JFrame {
    
    /**
     * Creates new form Studentnummer
     */
    public static BuchLeihenColumns2 buchLeihenColumns_objekt;
    ArrayList<BuchLeihenColumnsMitID> buch_leihen_bücherlist = new ArrayList<>();
    public Studentnummer() {
        initComponents();
        
        String pattern = "dd-MM-yyyy";
        String dateInString =new SimpleDateFormat(pattern).format(new Date());  
        datumFeld.setText(dateInString);
        //damit das Fenster in der Mitte vom Bildschirm stehen bleibt
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentnummerFeld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        SNBuchLeihenButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        datumFeld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Studentnummer eingeben");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\student.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Studentnummer :");

        studentnummerFeld.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentnummerFeld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentnummerFeldKeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\marmara_universitesi_logo.png")); // NOI18N

        SNBuchLeihenButton.setBackground(new java.awt.Color(51, 204, 255));
        SNBuchLeihenButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SNBuchLeihenButton.setText("weiter");
        SNBuchLeihenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SNBuchLeihenButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SNBuchLeihenButtonMouseExited(evt);
            }
        });
        SNBuchLeihenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNBuchLeihenButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Datum :");

        datumFeld.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SNBuchLeihenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(studentnummerFeld)
                            .addComponent(datumFeld)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentnummerFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datumFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(SNBuchLeihenButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentnummerFeldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentnummerFeldKeyTyped
        //Hier ermöglicht uns, dass man für Studentnummer maximal 10 Karakter benutzen darf.
        if((studentnummerFeld.getText() + evt.getKeyChar()).length() >= 10){
            evt.consume();
        }
        
        //Hier erlauben wir den User, dass er nur Nummer als Input eingibt
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_studentnummerFeldKeyTyped

    private void SNBuchLeihenButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNBuchLeihenButtonMouseEntered
        SNBuchLeihenButton.setBackground(new Color(0,100,200));
    }//GEN-LAST:event_SNBuchLeihenButtonMouseEntered

    private void SNBuchLeihenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SNBuchLeihenButtonMouseExited
        SNBuchLeihenButton.setBackground(new Color(51,204,255));
    }//GEN-LAST:event_SNBuchLeihenButtonMouseExited

    private void SNBuchLeihenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNBuchLeihenButtonActionPerformed
        
        if(!studentnummerFeld.getText().isEmpty()){
            BuchLeihenColumnsMitID buch_leihen_objekt;
            Bibliothek bibliothek_object = new Bibliothek();
            
            /*
            //int buchID = Integer.valueOf(bibliothek_object.BBuchIDfeld.getText());
            String namevonBuch = bibliothek_object.BNamevonBuchsFeld.getText();
            String author = bibliothek_object.BAutorsFeld.getText();
            String thema = bibliothek_object.BThemaFeld.getText();
            String verlag = bibliothek_object.BVerlagsFeld.getText();
            */
            String studentnummer = studentnummerFeld.getText();
            String datum = datumFeld.getText();
            
            buch_leihen_objekt = new BuchLeihenColumnsMitID(Integer.valueOf(buchLeihenColumns_objekt.getBuchID()),buchLeihenColumns_objekt.getBuchname(),buchLeihenColumns_objekt.getAuthor(),buchLeihenColumns_objekt.getAuflagesdatum(),
                            buchLeihenColumns_objekt.getThema(),buchLeihenColumns_objekt.getVerlag(),studentnummer,datum);
            buch_leihen_bücherlist.add(buch_leihen_objekt);

            PreparedStatement st;
            ResultSet rs;
            
            String SQLAnfrage = "INSERT INTO `buchleihen` (`buchID`,`buchname`,`author`,`auflagesdatum`,`thema`,`verlag`,`studentnummer`,`datum`) VALUES(?,?,?,?,?,?,?,?)";

            try {
                st = dBVerbindung.getConnection().prepareStatement(SQLAnfrage);
                
                st.setInt(1, buch_leihen_bücherlist.get(0).getBuchID());
                st.setString(2, buch_leihen_bücherlist.get(0).getBuchname());
                st.setString(3, buch_leihen_bücherlist.get(0).getAuthor());
                st.setString(4, buch_leihen_bücherlist.get(0).getAuflagesdatum());
                st.setString(5, buch_leihen_bücherlist.get(0).getThema());
                st.setString(6, buch_leihen_bücherlist.get(0).getVerlag());
                st.setString(7, buch_leihen_bücherlist.get(0).getStudentnummer());
                st.setString(8, buch_leihen_bücherlist.get(0).getDatum());
                
                //prüfen ob daten erfolgreich in System gespeichert werden
                if(st.executeUpdate()!=0){
                    JOptionPane.showMessageDialog(null, "Buch wurde dem Student geliehen.");
                    dispose();
                    //bücherdaten_live_zeigen();
                    //FelderSauberMachen();
                }
                
                new Bibliothek().setVisible(true);
            } catch (Exception e) {
                System.out.println(e);
            }

        }else{
            JOptionPane.showMessageDialog(null, "Jedes Feld muss vollständig erfüllt sein!","FEHLER",2);
        }
        
    }//GEN-LAST:event_SNBuchLeihenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentnummer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentnummer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentnummer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentnummer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentnummer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SNBuchLeihenButton;
    private javax.swing.JTextField datumFeld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField studentnummerFeld;
    // End of variables declaration//GEN-END:variables
}
