
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class Weiterleitungsfenster extends javax.swing.JFrame {

    /**
     * Creates new form Weiterleitungsfenster
     */
    public Weiterleitungsfenster() {
        initComponents();
        
        //nur ein Button sollte selektiert werden, darum erstellte sich eine Buttongruppe und wurde button drin gesteckt.
            ButtonGroup bg =new ButtonGroup();
                bg.add(admindatenRButton);
                bg.add(zurBibliothekRButton);
                bg.add(adminErstellenButton);
        
        //damit das Fenster in der Mitte vom Bildschirm stehen bleibt
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AdminDatenZeigenLabel = new javax.swing.JLabel();
        zurBibliothekGehenLabel = new javax.swing.JLabel();
        adminIcon = new javax.swing.JLabel();
        buchIcon = new javax.swing.JLabel();
        admindatenRButton = new javax.swing.JRadioButton();
        zurBibliothekRButton = new javax.swing.JRadioButton();
        abmeldenButton = new javax.swing.JButton();
        fortdauernButton = new javax.swing.JButton();
        adminErstellenLabel = new javax.swing.JLabel();
        adminErstellenIcon = new javax.swing.JLabel();
        adminErstellenButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weiterleitung ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Was möchten Sie jetzt tun ? ");

        AdminDatenZeigenLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminDatenZeigenLabel.setText("Admindaten zeigen");

        zurBibliothekGehenLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        zurBibliothekGehenLabel.setText("zur Bibliothek gehen");

        adminIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\admin (2).png")); // NOI18N
        adminIcon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminIconFocusGained(evt);
            }
        });
        adminIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminIconMouseExited(evt);
            }
        });

        buchIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\Buch.png")); // NOI18N
        buchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buchIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buchIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buchIconMouseExited(evt);
            }
        });

        admindatenRButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        admindatenRButton.setText("Admin daten zeigen");

        zurBibliothekRButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zurBibliothekRButton.setText("Zur Bibliothek gehen");

        abmeldenButton.setBackground(new java.awt.Color(51, 204, 255));
        abmeldenButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        abmeldenButton.setText("abmelden");
        abmeldenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abmeldenButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abmeldenButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abmeldenButtonMouseExited(evt);
            }
        });

        fortdauernButton.setBackground(new java.awt.Color(51, 204, 255));
        fortdauernButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fortdauernButton.setText("fortdauern");
        fortdauernButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fortdauernButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fortdauernButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fortdauernButtonMouseExited(evt);
            }
        });

        adminErstellenLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminErstellenLabel.setText("neuer Admin erstellen");

        adminErstellenIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\admin erstellen.png")); // NOI18N
        adminErstellenIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminErstellenIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminErstellenIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminErstellenIconMouseExited(evt);
            }
        });

        adminErstellenButton.setText("Admin erstellen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(adminIcon)
                .addGap(109, 109, 109)
                .addComponent(adminErstellenIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buchIcon)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdminDatenZeigenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(adminErstellenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(admindatenRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminErstellenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(zurBibliothekGehenLabel)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(zurBibliothekRButton)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(abmeldenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fortdauernButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminDatenZeigenLabel)
                    .addComponent(zurBibliothekGehenLabel)
                    .addComponent(adminErstellenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adminIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buchIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(adminErstellenIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admindatenRButton)
                    .addComponent(zurBibliothekRButton)
                    .addComponent(adminErstellenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(fortdauernButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abmeldenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminIconFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminIconFocusGained

    }//GEN-LAST:event_adminIconFocusGained

    private void adminIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminIconMouseEntered
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        Border border2 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        
        AdminDatenZeigenLabel.setForeground(Color.BLUE);
        AdminDatenZeigenLabel.setBorder(border);
        adminIcon.setBorder(border2);
    }//GEN-LAST:event_adminIconMouseEntered

    private void adminIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminIconMouseExited
        AdminDatenZeigenLabel.setBorder(null);
        AdminDatenZeigenLabel.setForeground(Color.BLACK);
        adminIcon.setBorder(null);
    }//GEN-LAST:event_adminIconMouseExited

    private void buchIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buchIconMouseEntered
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        Border border2 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        
        zurBibliothekGehenLabel.setForeground(Color.BLUE);
        zurBibliothekGehenLabel.setBorder(border);
        buchIcon.setBorder(border2);
    }//GEN-LAST:event_buchIconMouseEntered

    private void buchIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buchIconMouseExited
        zurBibliothekGehenLabel.setBorder(null);
        zurBibliothekGehenLabel.setForeground(Color.BLACK);
        buchIcon.setBorder(null);
    }//GEN-LAST:event_buchIconMouseExited

    private void adminIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminIconMouseClicked
        if(!admindatenRButton.isSelected()){
            //setSelected Methode ermöglicht es, das klicken wollende Button mit hilfe von Code zu selektieren
            admindatenRButton.setSelected(true);
        }
    }//GEN-LAST:event_adminIconMouseClicked

    private void buchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buchIconMouseClicked
        if(!zurBibliothekRButton.isSelected()){
            zurBibliothekRButton.setSelected(true);
        }
    }//GEN-LAST:event_buchIconMouseClicked

    private void abmeldenButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abmeldenButtonMouseEntered
        abmeldenButton.setForeground(new Color(255,255,255));
        abmeldenButton.setBackground(Color.red);
    }//GEN-LAST:event_abmeldenButtonMouseEntered

    private void abmeldenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abmeldenButtonMouseExited
        abmeldenButton.setForeground(Color.BLACK);
        abmeldenButton.setBackground(new Color(51,204,255));
    }//GEN-LAST:event_abmeldenButtonMouseExited

    private void fortdauernButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fortdauernButtonMouseEntered
        fortdauernButton.setBackground(new Color(0,100,200));
    }//GEN-LAST:event_fortdauernButtonMouseEntered

    private void fortdauernButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fortdauernButtonMouseExited
        fortdauernButton.setBackground(new Color(51,204,255));
    }//GEN-LAST:event_fortdauernButtonMouseExited

    private void abmeldenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abmeldenButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_abmeldenButtonMouseClicked

    private void fortdauernButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fortdauernButtonMouseClicked
        if(admindatenRButton.isSelected()){
            setVisible(false);
            new AdminDatenZeigen().setVisible(true);
        }
        else if(zurBibliothekRButton.isSelected()){
            setVisible(false);
            new Bibliothek().setVisible(true);
        }
        else if(adminErstellenButton.isSelected()){
            setVisible(false);
            new NeueAdminRegistrierung().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Sie müssen unbedingt ein Button selektieren!","Warnung",2);
        }
    }//GEN-LAST:event_fortdauernButtonMouseClicked

    private void adminErstellenIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminErstellenIconMouseEntered
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        Border border2 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        
        adminErstellenLabel.setForeground(Color.BLUE);
        adminErstellenLabel.setBorder(border);
        adminErstellenIcon.setBorder(border2);
    }//GEN-LAST:event_adminErstellenIconMouseEntered

    private void adminErstellenIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminErstellenIconMouseExited
        adminErstellenLabel.setBorder(null);
        adminErstellenLabel.setForeground(Color.BLACK);
        adminErstellenIcon.setBorder(null);
    }//GEN-LAST:event_adminErstellenIconMouseExited

    private void adminErstellenIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminErstellenIconMouseClicked
        if(!adminErstellenButton.isSelected()){
            //setSelected Methode ermöglicht es, das klicken wollende Button mit hilfe von Code zu selektieren
            adminErstellenButton.setSelected(true);
        }
    }//GEN-LAST:event_adminErstellenIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Weiterleitungsfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Weiterleitungsfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Weiterleitungsfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Weiterleitungsfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Weiterleitungsfenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDatenZeigenLabel;
    private javax.swing.JButton abmeldenButton;
    private javax.swing.JRadioButton adminErstellenButton;
    private javax.swing.JLabel adminErstellenIcon;
    private javax.swing.JLabel adminErstellenLabel;
    private javax.swing.JLabel adminIcon;
    private javax.swing.JRadioButton admindatenRButton;
    private javax.swing.JLabel buchIcon;
    private javax.swing.JButton fortdauernButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel zurBibliothekGehenLabel;
    private javax.swing.JRadioButton zurBibliothekRButton;
    // End of variables declaration//GEN-END:variables
}
