
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

public class Willkommen extends javax.swing.JFrame {

    /**
     * Creates new form Willkommen
     */
    public Willkommen(){
        initComponents();
        
        //damit das Fenster in der Mitte vom Bildschirm stehen bleibt
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        zugriffAufBibliothek = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\marmara kutuphane.jpg")); // NOI18N

        jButton3.setText("jButton3");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\marmara kutuphane.jpg")); // NOI18N
        jLabel4.setText("Zum Zugriff");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Willkommen zur Bibliothek der Marmara Universität");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 550, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\marmara_universitesi_logo.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 390, 120));

        zugriffAufBibliothek.setBackground(new java.awt.Color(102, 255, 255));
        zugriffAufBibliothek.setText("Zum Zugriff auf Bibliothek");
        zugriffAufBibliothek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zugriffAufBibliothekActionPerformed(evt);
            }
        });
        getContentPane().add(zugriffAufBibliothek, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 240, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Desktop\\Tulpar için\\Bachelorarbeit\\Icons & Bilder\\marmara kutuphane.jpg")); // NOI18N
        jLabel5.setText("Zum Zugriff");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zugriffAufBibliothekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zugriffAufBibliothekActionPerformed
        setVisible(false);
        new EingangsFenster().setVisible(true);
    }//GEN-LAST:event_zugriffAufBibliothekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /*
        int delay = 3000; // Delay in milliseconds

        Timer timer = new Timer(delay, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new Willkommen().setVisible(false);
                new ass().setVisible(true);
            }
        });
        timer.start();
        */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Willkommen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton zugriffAufBibliothek;
    // End of variables declaration//GEN-END:variables
}
